# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/surface/gui" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/surface/keyboard_driver" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/surface/rov_gazebo" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/surface/task_selector" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/pi/pixhawk_communication" # Location of package manifests
    schedule:
      interval: "daily"

      
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/workflows" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
