from launch_ros.actions import Node
from launch import LaunchDescription


def generate_launch_description():

    # Symlinks are auto-generated by V4L2
    # ls /dev/v4l/by-id to see all the available symlinks

    # USB 3.0
    front_cam_node: Node = Node(
        package="v4l2_camera",
        executable="v4l2_camera_node",
        namespace="front_cam",
        parameters=[
            {"video_device":
             "/dev/v4l/by-id/usb-3.0_USB_Camera_3.0_USB_Camera-video-index0"},
            {"image_size": [640, 480]}
        ],
        remappings=[("/pi/front_cam/image_raw", "/front_cam/image_raw"),
                    ("/pi/front_cam/image_raw/compressed", "/front_cam/image_raw/compressed"),
                    ("/pi/front_cam/image_raw/compressedDepth", "/front_cam/compressedDepth")]
    )

    # h264 (fisheye)
    bottom_cam_node: Node = Node(
        package="v4l2_camera",
        executable="v4l2_camera_node",
        namespace="bottom_cam",
        parameters=[
            {"video_device":
             "/dev/v4l/by-id/usb-H264_USB_Camera_H264_USB_Camera_2020032801-video-index0"},
            {"image_size": [640, 480]}
        ],
        remappings=[("/pi/bottom_cam/image_raw", "/bottom_cam/image_raw"),
                    ("/pi/bottom_cam/image_raw/compressed", "/bottom_cam/image_raw/compressed"),
                    ("/pi/bottom_cam/image_raw/compressedDepth", "/bottom_cam/compressedDepth")]
    )

    return LaunchDescription([
        front_cam_node,
        bottom_cam_node
    ])
