# https://github.com/ros-industrial/industrial_ci/blob/master/README.rst#id7
name: Continuous Integration

on: push

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: galactic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
